version: "3.9"

services:
  backend:
    image: ghcr.io/msrn/flask-demo-app-backend:latest
    ports:
      - "1337:1337"
    volumes:
      - ./test-mount:/app/data/
  frontend:
    image: ghcr.io/msrn/flask-demo-app-frontend:latest
    ports:
      - "8080:8080"
    environment:
      - BACKEND_SERVER=backend:1337
    depends_on:
      - backend
    