apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    name: frontend-pod
    app: frontend-pod
spec:
  containers:
  - name: frontend
    image: ghcr.io/msrn/flask-demo-app-frontend:latest
    env:
      - name: BACKEND_SERVER
        value: backend-service:1337
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-pod
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  #type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  labels:
    name: frontend-ingress
  annotations:
    route.openshift.io/termination: edge
spec:
  rules:
  - host: "frontend.msaarine.rahtiapp.fi"
    http:
      paths:
        - path: "/"
          backend:
            serviceName: frontend-service
            servicePort: 8080
